#
#  tmux.conf  --  TMux-Konfiguration
#

%if "#{==:#{ruby_support},1}"

run-ruby -n -F '$:.unshift "#{current_file}.d"'
run-ruby -n    'require "upinfo"'
run-ruby -n    'Tmux.battery = "BAT"'

set-option -g status-right '#{=-132:pane_title}  #(ruby:Tmux.upinfo hide: :s)  %H:%M %d.%m.%Y'


%endif

