#
#  tmux.conf  --  TMux-Konfiguration
#

%if "#{!=:#{lua_support},}"

run-lua -n -F 'package.path = package.path..";#{current_file}.d/?.lua"'

%if '#{m/r:\<5\.?[3-9]\>,#{lua_support}}'
run-lua -n    'ui = require("upinfo")'
run-lua -n    'ui.set_battery("BAT")'
%else
display-message 'Please edit upinfo.lua and make it #{lua_support} compatible.'
display-message 'Then remove this message.'
%endif

set-option -g status-right '#{=-132:pane_title}  #(lua:ui.upinfo({hide="s"}))  %H:%M %d.%m.%Y'


%endif

